# servekit/api — make targets for the contract repo.
#
# Discipline (CI enforces all of these):
#   1. proto files are the only source of truth; gen/ outputs are committed
#      artifacts regenerated by `make gen` and must never be hand-edited.
#   2. a PR is complete only when `make gen && git diff --exit-code` is clean.
#   3. `make breaking` guards wire compatibility against the latest tag.

BUF ?= buf

.PHONY: gen lint breaking fmt tidy build test clean

## gen: regenerate gen/go + gen/openapi (drops openapi stubs for
## annotation-less files — only testkit carries google.api.http annotations).
## buf's clean:true wipes gen/go including go.mod, so the module header is
## re-seeded here; tidy resolves the rest. Keeps `make gen` idempotent.
gen:
	$(BUF) generate --template buf.gen.go.yaml
	rm -rf gen/openapi/common gen/openapi/gid gen/openapi/license \
		gen/openapi/messaging gen/openapi/storage gen/openapi/telemetry \
		gen/openapi/user gen/openapi/testkit/v1/enums.swagger.json \
		gen/openapi/testkit/v1/message.swagger.json \
		gen/openapi/testkit/v1/request_response.swagger.json
	printf 'module github.com/servekit/api/gen/go\n\ngo 1.26.6\n' > gen/go/go.mod
	cd gen/go && go mod tidy && go build ./...

## lint: buf lint over the whole module.
lint:
	$(BUF) lint

## breaking: wire-compat check against the latest tag (or a base ref).
breaking:
	@base=$$(git describe --tags --abbrev=0 2>/dev/null || echo ""); \
	if [ -n "$$base" ]; then \
		$(BUF) breaking --against ".git#tag=$$base,subdir=$(CURDIR)"; \
	else \
		echo "breaking: no previous tag yet — skipping (first release)"; \
	fi

## fmt: canonical proto formatting.
fmt:
	$(BUF) format -w .

## tidy / build / test: Go-side of gen/go.
tidy:
	cd gen/go && go mod tidy

build:
	cd gen/go && go build ./...

test:
	cd gen/go && go test ./...
